# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: |
          npm install
          npm run build
      
      - name: Deploy
        uses: ItsKarma/aws-cli@v1.70.0
      - run: |
          export "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          export "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"
          export S3_BUCKET=$(aws ssm get-parameter --name /cosmos/${GITHUB_REF##*/}/s3/cosmos-front/id --region ${AWS_DEFAULT_REGION} --query 'Parameter.Value' --output text)
          export CLOUDFRONT_ID=$(aws ssm get-parameter --name /cosmos/${GITHUB_REF##*/}/cloudfront/id --region ${AWS_DEFAULT_REGION} --query 'Parameter.Value' --output text)
          aws s3 rm s3://${S3_BUCKET}/ --recursive
          aws s3 cp ./build/ s3://${S3_BUCKET}/ --recursive
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"

